
import java.awt.Graphics;
import java.awt.Image;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author carolina
 */
public class Number_race extends javax.swing.JFrame {
    FondoPanel background=new FondoPanel();
    int positions=0;
    int pairs=0;
    int turn=2;
    int player1_po=0;
    int player2_po=0;
    int pairsplayer2=0,pairsplayer1=0;
    //int turnplayer1,turnplayer2;
    /**
     * Creates new form NumberRace
     */
    
    public Number_race() {
        this.setContentPane(background);
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/icons/car.png")).getImage());
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new FondoPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cmbNumberPlayers = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cmbLevel = new javax.swing.JComboBox<>();
        btnPlay = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblDice1 = new javax.swing.JLabel();
        lblDice2 = new javax.swing.JLabel();
        btnPlayer = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lblTurn = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblPositions = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblMissing = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblReturn = new javax.swing.JLabel();
        btnConfig = new javax.swing.JButton();
        btnAgain = new javax.swing.JButton();
        btnAboutOf = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        lblPairs = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        lblWinner = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Number Race");
        setIconImages(null);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(251, 251, 251));
        jPanel1.setToolTipText("");
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(228, 107, 31));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Number race");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(228, 107, 31), 3, true), "Config zone", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("FreeSans", 3, 18), new java.awt.Color(228, 107, 31))); // NOI18N
        jPanel3.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("FreeSans", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(228, 107, 31));
        jLabel2.setText("Number of players:");

        cmbNumberPlayers.setBackground(new java.awt.Color(228, 107, 31));
        cmbNumberPlayers.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));

        jLabel3.setFont(new java.awt.Font("FreeSans", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(228, 107, 31));
        jLabel3.setText("Level:");

        cmbLevel.setBackground(new java.awt.Color(228, 107, 31));
        cmbLevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Basic", "Intermediate", "Advanced" }));

        btnPlay.setFont(new java.awt.Font("FreeSans", 3, 18)); // NOI18N
        btnPlay.setForeground(new java.awt.Color(250, 142, 8));
        btnPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/play_button.png"))); // NOI18N
        btnPlay.setText("Start game");
        btnPlay.setContentAreaFilled(false);
        btnPlay.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPlay.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/play_button.png"))); // NOI18N
        btnPlay.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/play_button2.png"))); // NOI18N
        btnPlay.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbNumberPlayers, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbLevel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(btnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbNumberPlayers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(228, 107, 31), 3, true), "Play zone", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("FreeSans", 3, 18), new java.awt.Color(228, 107, 31))); // NOI18N
        jPanel2.setOpaque(false);

        lblDice1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gifs/dado_in.gif"))); // NOI18N
        lblDice1.setBorder(null);

        lblDice2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gifs/dado_in.gif"))); // NOI18N
        lblDice2.setBorder(null);

        btnPlayer.setText("Play-Player #");
        btnPlayer.setEnabled(false);
        btnPlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblDice1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81)
                        .addComponent(lblDice2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblDice2, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(lblDice1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPlayer)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(228, 107, 31), 3, true), "Scores zone", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("FreeSans", 3, 18), new java.awt.Color(228, 107, 31))); // NOI18N
        jPanel4.setOpaque(false);

        jLabel6.setFont(new java.awt.Font("FreeSans", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(228, 107, 31));
        jLabel6.setText("Turn player:");

        lblTurn.setFont(new java.awt.Font("FreeSans", 3, 24)); // NOI18N
        lblTurn.setForeground(new java.awt.Color(254, 254, 254));
        lblTurn.setText("#");

        jLabel7.setFont(new java.awt.Font("FreeSans", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(228, 107, 31));
        jLabel7.setText("Advanced positions:");

        lblPositions.setFont(new java.awt.Font("FreeSans", 3, 24)); // NOI18N
        lblPositions.setForeground(new java.awt.Color(254, 254, 254));
        lblPositions.setText("#");

        jLabel8.setFont(new java.awt.Font("FreeSans", 3, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(228, 107, 31));
        jLabel8.setText("Missing positions:");

        lblMissing.setFont(new java.awt.Font("FreeSans", 3, 24)); // NOI18N
        lblMissing.setForeground(new java.awt.Color(254, 254, 254));
        lblMissing.setText("#");

        jLabel9.setFont(new java.awt.Font("FreeSans", 3, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(228, 107, 31));
        jLabel9.setText("Returns:");

        lblReturn.setFont(new java.awt.Font("FreeSans", 3, 24)); // NOI18N
        lblReturn.setForeground(new java.awt.Color(254, 254, 254));
        lblReturn.setText("#");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTurn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblReturn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPositions, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMissing, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 28, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblTurn))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblPositions))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblMissing))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lblReturn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnConfig.setText("Config params");
        btnConfig.setEnabled(false);
        btnConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfigActionPerformed(evt);
            }
        });

        btnAgain.setText("Try again");
        btnAgain.setEnabled(false);
        btnAgain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgainActionPerformed(evt);
            }
        });

        btnAboutOf.setText("About of");
        btnAboutOf.setEnabled(false);
        btnAboutOf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAboutOfActionPerformed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(228, 107, 31), 3, true), "Pairs", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("FreeSans", 3, 18), new java.awt.Color(228, 107, 31))); // NOI18N
        jPanel5.setOpaque(false);

        lblPairs.setFont(new java.awt.Font("FreeSans", 3, 24)); // NOI18N
        lblPairs.setForeground(new java.awt.Color(254, 254, 254));
        lblPairs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPairs.setText("0");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(lblPairs, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPairs, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(228, 107, 31), 3, true), "Winner", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("FreeSans", 3, 18), new java.awt.Color(228, 107, 31))); // NOI18N
        jPanel6.setOpaque(false);

        lblWinner.setFont(new java.awt.Font("FreeSans", 3, 24)); // NOI18N
        lblWinner.setForeground(new java.awt.Color(254, 254, 254));
        lblWinner.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWinner.setText("?");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblWinner, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblWinner, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnConfig, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnAgain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnAboutOf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(439, 439, 439)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(btnConfig)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAgain)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAboutOf)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        // TODO add your handling code here:
        btnAboutOf.setEnabled(true);
        btnAgain.setEnabled(true);
        btnConfig.setEnabled(true);
        btnPlayer.setEnabled(true);
        cmbNumberPlayers.setEnabled(false);
        cmbLevel.setEnabled(false);
        btnPlayer.setText("Play-Player 1");
        //lblTurn.setText("1");
        btnPlay.setEnabled(false);
    }//GEN-LAST:event_btnPlayActionPerformed

    private void btnPlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayerActionPerformed
        // Numbers random
        Random dices=new Random();
        int d1=0,d2=0;
        d1=(int)(dices.nextDouble()*6+1);
        d2=(int)(dices.nextDouble()*6+1);
        //dice1
        switch(d1){
            case 1:
                lblDice1.setIcon(new ImageIcon(getClass().getResource("/images/dice1.png")));
                break;
            case 2:
                lblDice1.setIcon(new ImageIcon(getClass().getResource("/images/dice2.png")));
                break;
            case 3:
                lblDice1.setIcon(new ImageIcon(getClass().getResource("/images/dice3.png")));
                break;
            case 4:
                lblDice1.setIcon(new ImageIcon(getClass().getResource("/images/dice4.png")));
                break;
            case 5:
                lblDice1.setIcon(new ImageIcon(getClass().getResource("/images/dice5.png")));
                break;
            case 6:
                lblDice1.setIcon(new ImageIcon(getClass().getResource("/images/dice6.png")));
                break;
            default:
                break;
        }
        
        //dice2
        switch(d2){
            case 1:
                lblDice2.setIcon(new ImageIcon(getClass().getResource("/images/dice1.png")));
                break;
            case 2:
                lblDice2.setIcon(new ImageIcon(getClass().getResource("/images/dice2.png")));
                break;
            case 3:
                lblDice2.setIcon(new ImageIcon(getClass().getResource("/images/dice3.png")));
                break;
            case 4:
                lblDice2.setIcon(new ImageIcon(getClass().getResource("/images/dice4.png")));
                break;
            case 5:
                lblDice2.setIcon(new ImageIcon(getClass().getResource("/images/dice5.png")));
                break;
            case 6:
                lblDice2.setIcon(new ImageIcon(getClass().getResource("/images/dice6.png")));
                break;
            default:
                break;
        }
        
        //Game Logic
        int missing_p=0,returns=0,missing_player2=0,missing_player1=0;
        //int level1[]=new int[50];
        int level2[]=new int[100];
        int level3[]=new int[200];
        //int turn_p;
        /*String turn="1";
        turn=cmbNumberPlayers.getSelectedItem().toString();
        turn_p=Integer.parseInt(turn);
        for(int i=0;i<=turn.length();i++){
            turn_p=i;
        }
        System.out.println("turno: "+turn_p);
        lblTurn.setText(Integer.toString(turn_p));*/
        String levels=cmbLevel.getSelectedItem().toString();
        //int nump=cmbNumberPlayers.getSelectedIndex();
        //int turn2[]=new int[nump];
        /*for(int i=0;i<=turn2.length;i++){
            lblTurn.setText(Integer.toString(i+1));
            System.out.println("turnos: "+i);
        }*/
        
        /*switch(levels){
            case "Basic":
                int level1[]=new int[50];
                do{
                for(int i=0;i<=turn2.length;i++){
                    lblTurn.setText(Integer.toString(i+1));
                    System.out.println("turnos: "+i);
                    if(){
                    }
                }
                }while(positions==50);
        }*/
        
        //----------------------------------------------------------------------
        int nump=Integer.parseInt(cmbNumberPlayers.getSelectedItem().toString());
        int player3_po=0;
        switch(levels){
            case "Basic":
                int level1[]=new int[50];
                if(nump==1){
                    positions+=(d1+d2);
                    lblPositions.setText(Integer.toString(positions));
                    //System.out.println("P: "+positions);
                    missing_p=(50-positions);
                    lblMissing.setText(Integer.toString(missing_p));
                    lblTurn.setText("1");
                if(d1==d2){
                    pairs++;
                    lblPairs.setText(Integer.toString(pairs));
                }
                }
                /*if(d1==d2){
                    pairs++;
                    lblPairs.setText(Integer.toString(pairs));
                }*/
                if(positions>=50){
                    lblWinner.setText("Player 1");
                    btnPlayer.setEnabled(false);
                    positions=0;
                }
                
                if(nump==2){
                    //do{
                                if(turn%2==0){
                                    lblTurn.setText("1");
                                    btnPlayer.setText("Play-Player 1");
                                    player1_po+=(d1+d2);
                                    lblPositions.setText(Integer.toString(player1_po));
                                    missing_player1=(50-player1_po);
                                    lblMissing.setText(Integer.toString(missing_player1));
                                    if(d1==d2){
                                        pairsplayer1++;
                                        lblPairs.setText(Integer.toString(pairsplayer1));
                                    }
                                }else{
                                    lblTurn.setText("2");
                                    btnPlayer.setText("Play-Player 2");
                                    player2_po+=(d1+d2);
                                    lblPositions.setText(Integer.toString(player2_po));
                                    missing_player2=(50-player2_po);
                                    lblMissing.setText(Integer.toString(missing_player2));
                                    if(d1==d2){
                                        pairsplayer2++;
                                        lblPairs.setText(Integer.toString(pairsplayer2));
                                    }
                                }
                                turn++;
                                if(player1_po>=50){
                                    lblWinner.setText("Player 1");
                                    btnPlayer.setEnabled(false);
                                    player1_po=0;
                                }
                                if(player2_po>=50){
                                    lblWinner.setText("Player 2");
                                    btnPlayer.setEnabled(false);
                                    player2_po=0;
                                }
                    //}while(player1_po==50);
                }
                
                break;
            case "Intermediate":
                break;
            case "Advanced":
                break;
                
        }
        
        
        
        
        
        
        
    }//GEN-LAST:event_btnPlayerActionPerformed

    private void btnConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfigActionPerformed
        // Config Params
        Config params=new Config();
        params.setVisible(true);
    }//GEN-LAST:event_btnConfigActionPerformed

    private void btnAboutOfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAboutOfActionPerformed
        // TODO add your handling code here:
        AboutOf information=new AboutOf();
        information.setVisible(true);
    }//GEN-LAST:event_btnAboutOfActionPerformed

    private void btnAgainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgainActionPerformed
        // TODO add your handling code here:
        btnAboutOf.setEnabled(false);
        btnConfig.setEnabled(false);
        btnPlayer.setEnabled(false);
        cmbNumberPlayers.setEnabled(true);
        cmbLevel.setEnabled(true);
        btnAgain.setEnabled(false);
        lblDice1.setIcon(new ImageIcon(getClass().getResource("/gifs/dado_in.gif")));
        lblDice2.setIcon(new ImageIcon(getClass().getResource("/gifs/dado_in.gif")));
        lblPositions.setText("#");
        lblTurn.setText("#");
        lblMissing.setText("#");
        lblPairs.setText("0");
        btnPlayer.setText("Play-Player #");
        btnPlay.setEnabled(true);
        lblWinner.setText("?");
        pairs=0;
        pairsplayer2=0;
        pairsplayer1=0;
        player1_po=0;
        player2_po=0;
        turn=2;
    }//GEN-LAST:event_btnAgainActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Number_race.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Number_race.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Number_race.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Number_race.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Number_race().setVisible(true);
            }
        });
    }
    //Background
    class FondoPanel extends JPanel{
        private Image fondo;
        @Override
        public void paint(Graphics g){
            fondo=new ImageIcon(getClass().getResource("/images/fondoGame.png")).getImage();
            g.drawImage(fondo, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAboutOf;
    private javax.swing.JButton btnAgain;
    private javax.swing.JButton btnConfig;
    private javax.swing.JButton btnPlay;
    private javax.swing.JButton btnPlayer;
    private javax.swing.JComboBox<String> cmbLevel;
    public static javax.swing.JComboBox<String> cmbNumberPlayers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lblDice1;
    private javax.swing.JLabel lblDice2;
    private javax.swing.JLabel lblMissing;
    private javax.swing.JLabel lblPairs;
    private javax.swing.JLabel lblPositions;
    private javax.swing.JLabel lblReturn;
    private javax.swing.JLabel lblTurn;
    private javax.swing.JLabel lblWinner;
    // End of variables declaration//GEN-END:variables
}
